Revert to old requirements & create sqlite db setup
- Django upgrade seems to have been causing an error when
    attempting to migrate:
        - AttributeError: 'CountryField' object has no attribute 'db_collation'

- reverted to old requirements with lower Django version

- migrate, create superuser, loaddata